### ISSUE TITLE
Can't position the snackbar horizontally on tablets

### ISSUE THREAD

**Issue by justincpollard** [nispok/snackbar#65]
Hi,

First of all, great library! I have a request: currently the snackbar is always positioned to the left of the screen on tablets. As a default, this works well, but if you're using the master/detail design pattern, more fine-grained control of the snackbar's location is needed to ensure that the snackbar doesn't cover critical information or straddle the master & detail views. Can you add a method to position the snackbar? Thanks!

**Comment by wmora** [comment]
@justincpollard Valid point, but I think this would get solved with #62. You would just display the Snackbar inside your detail view. What do you think?

**Comment by justincpollard** [comment]
Thanks for the response, @wmora! #62 gets part of the way there, but still doesn't allow true horizontal adjustment. For example, to align the snackbar to the right of a `ViewGroup`, I would need to make an invisible parent that aligns right. It's just a little extra hassle, but not impossible. Anyway, given #62, this issue isn't urgent.
